import type { Metadata } from "next";
import "./globals.css";
import dynamic from "next/dynamic";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
const SideBar = dynamic(() => import("@/components/sidebar"), { ssr: false });
const RightPage = dynamic(() => import("@/components/rightpage"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "WISE Edu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // hydration pass
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <Theme>
        <body className="overflow-y-auto overflow-x-hidden max-w-screen max-h-screen">
          <div className="grid grid-cols-12 min-h-screen">
            <div className="col-span-2 bg-[#F5ECD7] fixed min-h-screen">
              <SideBar />
            </div>

            {/* <!-- Faux Sidebar Space --> */}
            <div className="col-span-2 bg-[#F5ECD7] border-r-[1px] border-[#5e5e5e] min-h-screen"></div>

            <div className="col-span-6 bg-[#F5ECD7] min-h-screen">
              {children}
            </div>

            {/* <!-- Faux Sidebar Space --> */}
            <div className="col-span-4 bg-[#F5ECD7] min-h-screen"></div>

            <div className="fixed right-[60px] bg-[#F5ECD7] max-w-screen min-h-screen">
              <RightPage /> 
            </div>
          </div>
        </body>
      </Theme>
    </html>
  );
}
